### ISSUE TITLE
ReferenceError: buffer is not defined

### ISSUE THREAD

**Issue by mvasin** [imagemin/imagemin-jpegtran#10]
I get this error

```
/Users/username/Sites/process images/node_modules/imagemin-jpegtran/index.js:61
			if (err && (err.code !== 'EPIPE' || !isJpg(buffer))) {
			                                           ^

ReferenceError: buffer is not defined
    at ChildProcess.<anonymous> (/Users/mvasin/Sites/process images/node_modules/imagemin-jpegtran/index.js:61:47)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:817:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
```

every time I run this script
```
gulp.task('imagemin', () => {
    return gulp.src('src/**/*')
        .pipe(plumber({
            errorHandler: function (err) {
                gutil.beep();
                console.log(err);
               // this.emit('end');
            }
        }))
        .pipe(changed('dest'))
        .pipe(remember('all'))
        .pipe(imagemin({
            optimizationLevel: 2,
            progressive: true,
            svgoPlugins: [{removeViewBox: false}],
            use: [pngquant()]
        }))
        .pipe(gulp.dest('dest'))
        .pipe(cache('cache1', {optimizeMemory: true}))
        .pipe(remember('all'))
        .pipe(cache('cache1', {optimizeMemory: true}))
        .pipe(gulp.dest('dest'));
});
```
while working on 1,35GB directory of files.

**Comment by shinnn** [comment]
Fixed in https://github.com/imagemin/imagemin-jpegtran/commit/79e8f08c4959b82a8a5e65cce7283fb054437dce

**Comment by mvasin** [comment]
When the updated version will make it's way to NPM? Current v.3.3.4 doesn't include this update.

**Comment by shinnn** [comment]
Released as v4.3.2. https://github.com/imagemin/imagemin-jpegtran/commit/0e6a65806771792b7bb030c395f691615e6e7890

**Comment by mvasin** [comment]
I type `npm update imagemin-jpegtran`, then `npm -v imagemin-jpegtran` and see `3.3.4`. What do I do wrong?

**Comment by shinnn** [comment]
:point_right: https://stackoverflow.com/

That's not an issue with imagemin-jpegtran.
