### ISSUE TITLE
Error with options progressive or/and arithmetic

### ISSUE THREAD

**Issue by thisconnect** [imagemin/imagemin-jpegtran#19]
With progressive or/and arithmetic I get Requested feature was omitted at compile time error

without the options imageminJpegtran works fine.

OS X 10.11.5
Node.js v6.2.0

```
	.then(buffer => imagemin.buffer(buffer, {
		plugins: [imageminJpegtran({
			progressive: true,
			arithmetic: true
		})]
	}))
```

```
{ Error: Requested feature was omitted at compile time

    at ChildProcess.exithandler (child_process.js:202:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:850:16)
    at Socket.<anonymous> (internal/child_process.js:323:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:492:12)
  killed: false,
  code: 1,
  signal: null,
  cmd: 'node_modules/jpegtran-bin/vendor/jpegtran -copy none -optimize -progressive -arithmetic -outfile /var/folders/vc/g0g62cj15vg3vwyn3pdbp6bc0000gp/T/46ce5620-29c2-4872-9d6e-df4ab149ea89 /var/folders/vc/g0g62cj15vg3vwyn3pdbp6bc0000gp/T/b623691f-c9a4-4a9a-9f6d-3cdf3e87b83a',
  stdout: '',
  stderr: 'Requested feature was omitted at compile time\n' }

```

**Comment by kevva** [comment]
Oh, ok. We might need to recompile the binary for OS X then.

**Comment by thisconnect** [comment]
correction: the error only appears with `arithmetic: true`.

`progressive: true` works and does not error

**Comment by thisconnect** [comment]
```javascript
const imagemin = require('imagemin');
const imageminJpegtran = require('imagemin-jpegtran');

imagemin(['images/*.jpg'], 'build/', {
  use: [imageminJpegtran({
    progressive: false,
    arithmetic: true
  })]
})
.then(() => {
  console.log('Images optimized');
})
.catch(err => {
  console.log(err)
});
```

**Comment by kevva** [comment]
Yeah, the binary needs to be compiled with the `arithmetic` option enabled I think.

**Comment by thisconnect** [comment]
Is it compiled with `arithmetic` for other platforms or do they have the same problem?

**Comment by kevva** [comment]
It seems like `-optimize` and `-arithmetic` are mutually exclusive. So we can't use both. I'll fix that.

**Comment by thisconnect** [comment]
big thanks!
