### ISSUE TITLE
Error with latest version (v6.0.0) only

### ISSUE THREAD

**Issue by kevincaradant** [imagemin/imagemin-jpegtran#23]
Hi
I got this issue with the latest version of the plugin. Exactly this picture `onboarding-flow-mfa-1.jpg` can't be minify. The path is correct, there are 26 pictures before this error and that's work as expected but 5 pictures got this issue withtout any explanation.

The error: `Le chemin d'acc�s sp�cifi� est introuvable.`  can be translated by ` the specified path is not found` which is wrong

version node: V12.4.0
OS: Windows 10 64 bits

The previous version works perfectly 

```
(node:39388) UnhandledPromiseRejectionWarning: Error: Error in file: src/main/resources/conf/template/assets/img/onboarding-flow-mfa-1.jpg

Le chemin d'acc�s sp�cifi� est introuvable.

    at notFoundError (C:\Users\Documents\projets\federation\node_modules\execa\node_modules\cross-spawn\lib\enoent.js:11:11)
    at verifyENOENT (C:\Users\Documents\projets\federation\node_modules\execa\node_modules\cross-spawn\lib\enoent.js:46:16)
    at ChildProcess.cp.emit (C:\Users\Documents\projets\federation\node_modules\execa\node_modules\cross-spawn\lib\enoent.js:33:19)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
(node:39388) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 6)
(node:39388) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Done in 3.36s.
```

**Comment by yangchongduo** [comment]
If you let everyone use it, please maintain it
imagemin has changed
imagemin-jpegtran has not changed
Report error via node 12. *. *
