### ISSUE TITLE
npm install has a bug

### ISSUE THREAD

**Issue by XiaoLizi29** [imagemin/imagemin-jpegtran#30]
$ npm install --save imagemin-jpegtran

> jpegtran-bin@5.0.2 postinstall C:\Users\23973\Desktop\公司项目\nanwudi-H5\node_modules\jpegtran-bin
> node lib/install.js

  ‼ getaddrinfo ENOENT raw.githubusercontent.com
  ‼ jpegtran pre-build test failed
  i compiling from source
  × Error: Command failed: C:\Windows\system32\cmd.exe /s /c "./configure --disable-shared --prefix="C:\Users\23973\Desktop\公司项目\nanwudi-H5\node_modules\jpegtran-bin\vendor" --bindir="C:\Users\23973\Desktop\公司项目\nanwudi-H5\node_modules\jpegtran-bin\vendor""
'.' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
���������ļ���

    at C:\Users\23973\Desktop\公司项目\nanwudi-H5\node_modules\bin-build\node_modules\execa\index.js:231:11
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Promise.all (index 0)
npm WARN eslint-config-vue@2.0.2 requires a peer of eslint@^2.0.0 || ^3.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-config-vue@2.0.2 requires a peer of eslint-plugin-vue@^1.0.0 || ^2.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.12 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.12: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! jpegtran-bin@5.0.2 postinstall: `node lib/install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the jpegtran-bin@5.0.2 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\23973\AppData\Roaming\npm-cache\_logs\2020-11-09T05_37_17_181Z-debug.log

**Comment by Minori-ty** [comment]
I have the same problem
